check only if JAVA_HOME path exists

diff --git a/liquibase-dist/src/main/archive/liquibase b/liquibase-dist/src/main/archive/liquibase
--- a/liquibase-dist/src/main/archive/liquibase
+++ b/liquibase-dist/src/main/archive/liquibase
@@ -31,9 +31,9 @@ if [ -z "${JAVA_HOME}" ]; then
     JAVA_HOME="${LIQUIBASE_HOME}/.install4j/jre.bundle/Contents/Home"
   fi
 else
-  if [[ $JAVA_HOME == *";"* ]]; then
-    #JAVA_HOME is set, use only the first JAVA_HOME in the semicolon separated list
-    JAVA_HOME=$(echo "$JAVA_HOME" | cut -d ";" -f 1)
+  if [ ! -x "$JAVA_HOME" ] ; then
+    echo "ERROR: Liquibase cannot determine a valid JAVA_PATH or JAVA_HOME. Please inspect your configurations and try again." >&2
+    exit 1
   fi
 fi
 
