formatting build yml files

diff --git a/.github/workflows/build-branch.yml b/.github/workflows/build-branch.yml
--- a/.github/workflows/build-branch.yml
+++ b/.github/workflows/build-branch.yml
@@ -5,9 +5,62 @@ on:
   push:
     branches-ignore:
       - master
+
 env:
   MAVEN_VERSION: '3.9.2'
+
 jobs:
+  build:
+    name: Build & Package
+    runs-on: ubuntu-22.04
+    needs: setup
+    permissions:
+      contents: read
+      packages: write
+
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Find mvn Build Attributes
+        id: find-attributes
+        uses: actions/github-script@v6
+        with:
+          github-token: ${{ secrets.BOT_TOKEN }}
+          script: |
+            const helper = require('./.github/util/workflow-helper.js')({github, context});
+
+            core.setOutput("thisSha", helper.getCurrentSha());
+            core.setOutput("thisBranchName", helper.getCurrentBranch());
+            core.setOutput("thisRepoName", helper.getRepositoryName());
+            core.setOutput("thisRepoOwner", helper.getRepositoryOwner());
+
+      - uses: actions/checkout@v3
+
+      - name: Set up Java for publishing to GitHub Repository
+        uses: actions/setup-java@v3
+        with:
+          java-version: '17'
+          distribution: 'temurin'
+          cache: 'maven'
+          server-id: liquibase
+
+      - name: Set up Maven
+        uses: stCarolas/setup-maven@v4.5
+        with:
+          maven-version: ${{ env.MAVEN_VERSION }}
+
+      # Version artifact based off of branch and commit SHA.
+      - name: Version Artifact
+        run: mvn versions:set -DnewVersion="${{ github.ref_name }}-SNAPSHOT"
+
+      # This would still deploy a package if there are test failures. Might help to have build.yml complete and then run this workflow
+      # Publish to GitHub Packages
+      - name: Publish package
+        run: |
+          mvn -B clean deploy -pl '!liquibase-dist' -DskipTests=true "-Dbuild.repository.owner=${{ needs.setup.outputs.thisRepositoryOwner }}" "-Dbuild.repository.name=${{ needs.setup.outputs.thisRepositoryName }}" "-Dbuild.branch=${{ needs.setup.outputs.thisBranchName }}" "-Dbuild.number=${{ github.run_number }}" "-Dbuild.commit=${{ needs.setup.outputs.thisSha }}" "-Dbuild.timestamp=${{ github.run_created }}"
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
   setup:
     name: Setup
     runs-on: ubuntu-22.04
@@ -16,18 +69,13 @@ jobs:
       thisBranchName: ${{ steps.find-attributes.outputs.thisBranchName }}
       thisBranchFileName: ${{ steps.find-attributes.outputs.thisBranchFileName }}
       thisRepositoryName: ${{ steps.find-attributes.outputs.thisRepositoryName }}
-      thisRepositoryOwner: ${{ steps.find-attributes.outputs.thisRepositoryName }}
+      thisRepositoryOwner: ${{ steps.find-attributes.outputs.thisRepositoryOwner }}
       setupSuccessful: "true"
-  build:
-    name: Build & Package
-    runs-on: ubuntu-22.04
-    permissions:
-      contents: read
-      packages: write
+
     steps:
       - uses: actions/checkout@v3
         with:
-          ref: ${{ github.event.pull_request.head.sha || github.event.after}}
+          ref: ${{ github.event.pull_request.head.sha || github.event.after }}
 
       - name: Find mvn Build Attributes
         id: find-attributes
@@ -40,33 +88,5 @@ jobs:
             core.setOutput("thisSha", helper.getCurrentSha());
             core.setOutput("thisBranchName", helper.getCurrentBranch());
             core.setOutput("thisBranchFileName", helper.getCurrentBranch().replace(/[^a-zA-Z0-9\-_]/g, "_"));
-            core.setOutput("thisRepoName", helper.getRepositoryName());
-            core.setOutput("thisRepoOwner", helper.getRepositoryOwner());
-            
-
-      - uses: actions/checkout@v3
-
-      - name: Set up Java for publishing to GitHub Repository
-        uses: actions/setup-java@v3
-        with:
-          java-version: '17'
-          distribution: 'temurin'
-          cache: 'maven'
-          server-id: liquibase
-      - name: Set up Maven
-        uses: stCarolas/setup-maven@v4.5
-        with:
-          maven-version: ${{ env.MAVEN_VERSION }}
-
-      # Version artifact based off of branch and commit SHA.
-      - name: Version Artifact
-        run: mvn versions:set -DnewVersion="${{ github.ref_name }}-SNAPSHOT"
-
-
-      # This would still deploy a package if there are test failures. Might help to have build.yml complete and then run this workflow
-      # Publish to GitHub Packages
-      - name: Publish package
-        run: |
-          mvn -B clean deploy -pl '!liquibase-dist' -DskipTests=true "-Dbuild.repository.owner=${{ needs.setup.outputs.thisRepositoryOwner }}" "-Dbuild.repository.name=${{ needs.setup.outputs.thisRepositoryName }}" "-Dbuild.branch=${{ needs.setup.outputs.thisBranchName }}" "-Dbuild.number=${{ github.run_number }}" "-Dbuild.commit=${{ needs.setup.outputs.thisSha }}" "-Dbuild.timestamp=${{ steps.date.outputs.date }}"
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+            core.setOutput("thisRepositoryName", helper.getRepositoryName());
+            core.setOutput("thisRepositoryOwner", helper.getRepositoryOwner());
