fix: Update branch handling in build process for extensions

diff --git a/.github/workflows/build-extension-jars.yml b/.github/workflows/build-extension-jars.yml
--- a/.github/workflows/build-extension-jars.yml
+++ b/.github/workflows/build-extension-jars.yml
@@ -371,7 +371,15 @@ jobs:
           GPG_PASSWORD: ${{ secrets.GPG_PASSPHRASE }}
         continue-on-error: true
         run: |
-          scripts_branch=${{ needs.matching-branch-logic-extensions.outputs.extensions_branch }}
+          matching_branch=${{ needs.matching-branch-logic-extensions.outputs.extensions_branch }}
+          # if matching_branch is main set liqubase_branch to master as liquibase has no main branch
+
+          if [ "$matching_branch" == "main" ]; then
+            liquibase_branch="master"
+          else
+            liquibase_branch=$matching_branch
+          fi
+          
           git config --global credential.helper store
           echo "https://$GIT_USERNAME:$GIT_PASSWORD@github.com" > ~/.git-credentials
           IFS=',' read -ra EXT_ARRAY <<< "${{ inputs.extensions }}"
@@ -381,7 +389,7 @@ jobs:
               echo "Checking out and building $ext"
               git clone https://github.com/liquibase/$ext.git $ext
               cd $ext
-              git checkout $scripts_branch || echo "Branch $scripts_branch not found, staying on default"
+              git checkout $matching_branch || echo "Branch $matching_branch not found, staying on default"
               git branch -a
               sed -i "s/<liquibase.version>.*<\/liquibase.version>/<liquibase.version>0-SNAPSHOT<\/liquibase.version>/" pom.xml
               mvn versions:set -DnewVersion=0-SNAPSHOT
@@ -395,11 +403,11 @@ jobs:
               echo $ext
               mkdir -p $PWD/.github/util/
               echo "before 1st curl"
-              curl -o $PWD/.github/util/re-version.sh https://raw.githubusercontent.com/liquibase/liquibase/$scripts_branch/.github/util/re-version.sh
+              curl -o $PWD/.github/util/re-version.sh https://raw.githubusercontent.com/liquibase/liquibase/$liquibase_branch/.github/util/re-version.sh
               echo "after 1st curl"
-              curl -o $PWD/.github/util/sign-artifacts.sh https://raw.githubusercontent.com/liquibase/liquibase/$scripts_branch/.github/util/sign-artifacts.sh
+              curl -o $PWD/.github/util/sign-artifacts.sh https://raw.githubusercontent.com/liquibase/liquibase/$liquibase_branch/.github/util/sign-artifacts.sh
               echo "before 2 curl"
-              curl -o $PWD/.github/util/ManifestReversion.java https://raw.githubusercontent.com/liquibase/liquibase/$scripts_branch/.github/util/ManifestReversion.java
+              curl -o $PWD/.github/util/ManifestReversion.java https://raw.githubusercontent.com/liquibase/liquibase/$liquibase_branch/.github/util/ManifestReversion.java
               echo "after 2 curl"
               chmod +x $PWD/.github/util/re-version.sh
               chmod +x $PWD/.github/util/sign-artifacts.sh
