🔧 (create-release.yml): comment out build-azure-uber-jar job as it is currently not needed and can be re-enabled later if required.
🔧 (create-release.yml): Update workflow to checkout liquibase-bigquery repository and re-version BigQuery extensions for build and installation.

📝: Comment out unused code related to saving keys and rebuilding installers
🔧: Comment out attaching files to draft release and signing files to prevent unnecessary actions in the workflow

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -33,13 +33,13 @@ jobs:
       - run: |
           echo "Creating version ${{ steps.collect-data.outputs.version }} from ${{ steps.collect-data.outputs.branch }} with artifacts from build ${{ steps.collect-data.outputs.runId }} "
           
-  build-azure-uber-jar:
-   needs: [ setup ]
-   uses: liquibase/liquibase/.github/workflows/build-azure-uber-jar.yml@master
-   with:
-     branch: ${{ needs.setup.outputs.branch }}
-     liquibase-version: ${{ needs.setup.outputs.version }}
-   secrets: inherit
+  # build-azure-uber-jar:
+  #  needs: [ setup ]
+  #  uses: liquibase/liquibase/.github/workflows/build-azure-uber-jar.yml@master
+  #  with:
+  #    branch: ${{ needs.setup.outputs.branch }}
+  #    liquibase-version: ${{ needs.setup.outputs.version }}
+  #  secrets: inherit
   
 
   reversion:
@@ -89,126 +89,160 @@ jobs:
           gpg-passphrase: GPG_PASSPHRASE
         env:
           GPG_PASSWORD: ${{ secrets.GPG_PASSPHRASE }}
-
-      - name: Re-version Artifacts
-        env:
-          GPG_PASSWORD: ${{ secrets.GPG_PASSPHRASE }}
-        run: |
-          scripts_branch=${{ github.ref }}
-          mkdir -p $PWD/.github/util/
-          # Download a script (re-version.sh) from a URL and save it to the specified directory
-          curl -o $PWD/.github/util/re-version.sh https://raw.githubusercontent.com/liquibase/liquibase/$scripts_branch/.github/util/re-version.sh
           
-          # Download another script (sign-artifacts.sh) from a URL and save it to the specified directory
-          curl -o $PWD/.github/util/sign-artifacts.sh https://raw.githubusercontent.com/liquibase/liquibase/$scripts_branch/.github/util/sign-artifacts.sh
-          curl -o $PWD/.github/util/ManifestReversion.java https://raw.githubusercontent.com/liquibase/liquibase/$scripts_branch/.github/util/ManifestReversion.java
-          chmod +x $PWD/.github/util/re-version.sh
-          chmod +x $PWD/.github/util/ManifestReversion.java
-          chmod +x $PWD/.github/util/sign-artifacts.sh
-          $PWD/.github/util/re-version.sh download/liquibase-artifacts "${{ needs.setup.outputs.version }}" "${{ needs.setup.outputs.branch }}"
-
-          # Execute the sign-artifacts.sh script with specific arguments
-          $PWD/.github/util/sign-artifacts.sh download/liquibase-artifacts "${{ needs.setup.outputs.version }}" "${{ needs.setup.outputs.branch }}"
-          
-          ##Sign Files
-          ## liquibase-azure-deps is already on its correct version. Check reusable workflow: build-azure-uber-jar.yml
-          mv liquibase-pro/liquibase-azure-deps/* re-version/out
-          
-          $PWD/.github/util/sign-artifacts.sh re-version/out
-          
-          # Move files to a specific directory
-          mkdir re-version/final
-          mv re-version/out/liquibase-core-${{ needs.setup.outputs.version }}.jar re-version/final
-          mv re-version/out/liquibase-commercial-${{ needs.setup.outputs.version }}.jar re-version/final
-          mv re-version/out/liquibase-${{ needs.setup.outputs.version }}.tar.gz re-version/final
-          mv re-version/out/liquibase-${{ needs.setup.outputs.version }}.zip re-version/final
-          mv re-version/out/liquibase-azure-deps-${{ needs.setup.outputs.version }}.jar re-version/final/liquibase-azure-deps-${{ needs.setup.outputs.version }}.jar
-          
-          (cd re-version/out/ && zip liquibase-additional-${{ needs.setup.outputs.version }}.zip *)
-          mv re-version/out/liquibase-additional-${{ needs.setup.outputs.version }}.zip re-version/final
-      - name: Cache Completed Artifacts
-        uses: actions/cache@v4.0.2
-        with:
-          key: completed-artifacts-${{ github.run_number }}-${{ github.run_attempt }}
-          path: re-version/final
-
-      - name: Set repository tags
-        run: |
-          git tag -f v${{ needs.setup.outputs.version }}
-          git push -f origin v${{ needs.setup.outputs.version }}
-          (cd download/repo/liquibase-pro && git tag -f v${{ needs.setup.outputs.version }})
-          (cd download/repo/liquibase-pro && git push -f origin v${{ needs.setup.outputs.version }})
-
-  build-installers:
-    permissions:
-      contents: write  # for softprops/action-gh-release to create GitHub release
-    needs: [ setup, reversion ]
-    name: Build Installers
-    runs-on: macos-13 #needs macos for apple notarization
-    env:
-      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-    steps:
       - uses: actions/checkout@v4
-
-      - name: Restore Completed Artifacts
-        uses: actions/cache@v4.0.2
+        name: Checkout liquibase-bigquery
         with:
-          key: completed-artifacts-${{ github.run_number }}-${{ github.run_attempt }}
-          path: re-version/final
-
-      - name: Set up JDK for GPG
-        uses: actions/setup-java@v4
+          repository: liquibase/liquibase-bigquery
+          ref: main
+          token: ${{ secrets.BOT_TOKEN }}
+          path: liquibase-bigquery
+          
+      - uses: actions/checkout@v4
+        name: Checkout liquibase-commercial-bigquery
         with:
-          java-version: '8'
-          distribution: 'adopt'
-          gpg-private-key: ${{ secrets.GPG_SECRET }}
-          gpg-passphrase: GPG_PASSPHRASE
-        env:
-          GPG_PASSWORD: ${{ secrets.GPG_PASSPHRASE }}
-
-
-      - name: Re-version Installers
-        env:
-          INSTALL4J_10_LICENSE: ${{ secrets.INSTALL4J_10_LICENSE }}
-          INSTALL4J_APPLE_KEY: ${{ secrets.INSTALL4J_APPLE_KEY }}
-          INSTALL4J_APPLE_KEY_PASSWORD: ${{ secrets.INSTALL4J_APPLE_KEY_PASSWORD }}
-          INSTALL4J_APPLE_ID: ${{ secrets.INSTALL4J_APPLE_ID }}
-          INSTALL4J_APPLE_ID_PASSWORD: ${{ secrets.INSTALL4J_APPLE_ID_PASSWORD }}
-          INSTALL4J_WINDOWS_KEY: ${{ secrets.INSTALL4J_WINDOWS_KEY }}
-          INSTALL4J_WINDOWS_KEY_PASSWORD: ${{ secrets.INSTALL4J_WINDOWS_KEY_PASSWORD }}
-          GPG_PASSWORD: ${{ secrets.GPG_PASSPHRASE }}
+          repository: liquibase/liquibase-bigquery
+          ref: main
+          token: ${{ secrets.BOT_TOKEN }}
+          path: liquibase-commercial-bigquery
+          
+      - name: Re-version BigQuery extensions
         run: |
-          mkdir -p liquibase-dist/target/keys
-          echo "Saving apple key"
-          echo "$INSTALL4J_APPLE_KEY" | base64 -d > liquibase-dist/target/keys/datical_apple.p12
-          echo "Saving windows key"
-          echo "$INSTALL4J_WINDOWS_KEY" | base64 -d > liquibase-dist/target/keys/datical_windows.pfx
-          version="${{ needs.setup.outputs.version }}"
+          cd liquibase-bigquery
+          mvn versions:set -DnewVersion=${{ needs.setup.outputs.version }}
+          cd ..
+          cd liquibase-commercial-bigquery
+          mvn versions:set -DnewVersion=${{ needs.setup.outputs.version }}
+          cd ..
           
-          ##### Rebuild installers
-          tarFile=$(pwd)/re-version/final/liquibase-$version.tar.gz
-          scriptDir=$(pwd)/.github/util/
+      - name: Build and install BigQuery extensions
+        run: |
+          cd liquibase-bigquery
+          mvn clean install -DskipTests
+          cd ..
+          cd liquibase-commercial-bigquery
+          mvn clean install -DskipTests
+          cd ..
+
+  #     - name: Re-version Artifacts
+  #       env:
+  #         GPG_PASSWORD: ${{ secrets.GPG_PASSPHRASE }}
+  #       run: |
+  #         scripts_branch=${{ github.ref }}
+  #         mkdir -p $PWD/.github/util/
+  #         # Download a script (re-version.sh) from a URL and save it to the specified directory
+  #         curl -o $PWD/.github/util/re-version.sh https://raw.githubusercontent.com/liquibase/liquibase/$scripts_branch/.github/util/re-version.sh
           
-          mkdir -p liquibase-dist/target/liquibase-$version
-          (cd liquibase-dist/target/liquibase-$version && tar xfz $tarFile)
-          (cd liquibase-dist && $scriptDir/package-install4j.sh $version)
-          mv liquibase-dist/target/liquibase-*-installer-* re-version/final
+  #         # Download another script (sign-artifacts.sh) from a URL and save it to the specified directory
+  #         curl -o $PWD/.github/util/sign-artifacts.sh https://raw.githubusercontent.com/liquibase/liquibase/$scripts_branch/.github/util/sign-artifacts.sh
+  #         curl -o $PWD/.github/util/ManifestReversion.java https://raw.githubusercontent.com/liquibase/liquibase/$scripts_branch/.github/util/ManifestReversion.java
+  #         chmod +x $PWD/.github/util/re-version.sh
+  #         chmod +x $PWD/.github/util/ManifestReversion.java
+  #         chmod +x $PWD/.github/util/sign-artifacts.sh
+  #         $PWD/.github/util/re-version.sh download/liquibase-artifacts "${{ needs.setup.outputs.version }}" "${{ needs.setup.outputs.branch }}"
+
+  #         # Execute the sign-artifacts.sh script with specific arguments
+  #         $PWD/.github/util/sign-artifacts.sh download/liquibase-artifacts "${{ needs.setup.outputs.version }}" "${{ needs.setup.outputs.branch }}"
           
-          ##Sign Files
-          $PWD/.github/util/sign-artifacts.sh re-version/final
+  #         ##Sign Files
+  #         ## liquibase-azure-deps is already on its correct version. Check reusable workflow: build-azure-uber-jar.yml
+  #         mv liquibase-pro/liquibase-azure-deps/* re-version/out
           
-          (cd re-version/final && zip liquibase-additional-$version.zip *.asc *.md5 *.sha1)
-          rm re-version/final/*.asc
-          rm re-version/final/*.md5
-          rm re-version/final/*.sha1
-      - name: Attach Files to Draft Release
-        uses: softprops/action-gh-release@v2
-        with:
-          tag_name: v${{ needs.setup.outputs.version }}
-          fail_on_unmatched_files: true
-          body: Liquibase ${{ needs.setup.outputs.version }}
-          generate_release_notes: true
-          draft: true
-          files: re-version/final/*
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #         $PWD/.github/util/sign-artifacts.sh re-version/out
+          
+  #         # Move files to a specific directory
+  #         mkdir re-version/final
+  #         mv re-version/out/liquibase-core-${{ needs.setup.outputs.version }}.jar re-version/final
+  #         mv re-version/out/liquibase-commercial-${{ needs.setup.outputs.version }}.jar re-version/final
+  #         mv re-version/out/liquibase-${{ needs.setup.outputs.version }}.tar.gz re-version/final
+  #         mv re-version/out/liquibase-${{ needs.setup.outputs.version }}.zip re-version/final
+  #         mv re-version/out/liquibase-azure-deps-${{ needs.setup.outputs.version }}.jar re-version/final/liquibase-azure-deps-${{ needs.setup.outputs.version }}.jar
+          
+  #         (cd re-version/out/ && zip liquibase-additional-${{ needs.setup.outputs.version }}.zip *)
+  #         mv re-version/out/liquibase-additional-${{ needs.setup.outputs.version }}.zip re-version/final
+  #     - name: Cache Completed Artifacts
+  #       uses: actions/cache@v4.0.2
+  #       with:
+  #         key: completed-artifacts-${{ github.run_number }}-${{ github.run_attempt }}
+  #         path: re-version/final
+
+  #     - name: Set repository tags
+  #       run: |
+  #         git tag -f v${{ needs.setup.outputs.version }}
+  #         git push -f origin v${{ needs.setup.outputs.version }}
+  #         (cd download/repo/liquibase-pro && git tag -f v${{ needs.setup.outputs.version }})
+  #         (cd download/repo/liquibase-pro && git push -f origin v${{ needs.setup.outputs.version }})
+
+  # build-installers:
+  #   permissions:
+  #     contents: write  # for softprops/action-gh-release to create GitHub release
+  #   needs: [ setup, reversion ]
+  #   name: Build Installers
+  #   runs-on: macos-13 #needs macos for apple notarization
+  #   env:
+  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #   steps:
+  #     - uses: actions/checkout@v4
+
+  #     - name: Restore Completed Artifacts
+  #       uses: actions/cache@v4.0.2
+  #       with:
+  #         key: completed-artifacts-${{ github.run_number }}-${{ github.run_attempt }}
+  #         path: re-version/final
+
+  #     - name: Set up JDK for GPG
+  #       uses: actions/setup-java@v4
+  #       with:
+  #         java-version: '8'
+  #         distribution: 'adopt'
+  #         gpg-private-key: ${{ secrets.GPG_SECRET }}
+  #         gpg-passphrase: GPG_PASSPHRASE
+  #       env:
+  #         GPG_PASSWORD: ${{ secrets.GPG_PASSPHRASE }}
+
+
+  #     - name: Re-version Installers
+  #       env:
+  #         INSTALL4J_10_LICENSE: ${{ secrets.INSTALL4J_10_LICENSE }}
+  #         INSTALL4J_APPLE_KEY: ${{ secrets.INSTALL4J_APPLE_KEY }}
+  #         INSTALL4J_APPLE_KEY_PASSWORD: ${{ secrets.INSTALL4J_APPLE_KEY_PASSWORD }}
+  #         INSTALL4J_APPLE_ID: ${{ secrets.INSTALL4J_APPLE_ID }}
+  #         INSTALL4J_APPLE_ID_PASSWORD: ${{ secrets.INSTALL4J_APPLE_ID_PASSWORD }}
+  #         INSTALL4J_WINDOWS_KEY: ${{ secrets.INSTALL4J_WINDOWS_KEY }}
+  #         INSTALL4J_WINDOWS_KEY_PASSWORD: ${{ secrets.INSTALL4J_WINDOWS_KEY_PASSWORD }}
+  #         GPG_PASSWORD: ${{ secrets.GPG_PASSPHRASE }}
+  #       run: |
+  #         mkdir -p liquibase-dist/target/keys
+  #         echo "Saving apple key"
+  #         echo "$INSTALL4J_APPLE_KEY" | base64 -d > liquibase-dist/target/keys/datical_apple.p12
+  #         echo "Saving windows key"
+  #         echo "$INSTALL4J_WINDOWS_KEY" | base64 -d > liquibase-dist/target/keys/datical_windows.pfx
+  #         version="${{ needs.setup.outputs.version }}"
+          
+  #         ##### Rebuild installers
+  #         tarFile=$(pwd)/re-version/final/liquibase-$version.tar.gz
+  #         scriptDir=$(pwd)/.github/util/
+          
+  #         mkdir -p liquibase-dist/target/liquibase-$version
+  #         (cd liquibase-dist/target/liquibase-$version && tar xfz $tarFile)
+  #         (cd liquibase-dist && $scriptDir/package-install4j.sh $version)
+  #         mv liquibase-dist/target/liquibase-*-installer-* re-version/final
+          
+  #         ##Sign Files
+  #         $PWD/.github/util/sign-artifacts.sh re-version/final
+          
+  #         (cd re-version/final && zip liquibase-additional-$version.zip *.asc *.md5 *.sha1)
+  #         rm re-version/final/*.asc
+  #         rm re-version/final/*.md5
+  #         rm re-version/final/*.sha1
+  #     - name: Attach Files to Draft Release
+  #       uses: softprops/action-gh-release@v2
+  #       with:
+  #         tag_name: v${{ needs.setup.outputs.version }}
+  #         fail_on_unmatched_files: true
+  #         body: Liquibase ${{ needs.setup.outputs.version }}
+  #         generate_release_notes: true
+  #         draft: true
+  #         files: re-version/final/*
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
