🔧 (create-release.yml): re-enable owasp-scanner and build-azure-uber-jar workflows 🔧 (create-release.yml): fix indentation issue in build-azure-uber-jar job 🔧 (create-release.yml): fix command to move liquibase-azure-deps files in sign files section 🔧 (create-release.yml): fix command to create directory before extracting tar.gz file and copying extension jars

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -53,23 +53,23 @@ jobs:
       - run: |
           echo "Creating version ${{ steps.collect-data.outputs.version }} from ${{ steps.collect-data.outputs.branch }} with artifacts from build ${{ steps.collect-data.outputs.runId }} "
           
-  # owasp-scanner:
-  #   needs: [ setup ]
-  #   uses: liquibase/build-logic/.github/workflows/owasp-scanner.yml@main
-  #   with:
-  #     branch: ${{ needs.setup.outputs.branch }}
-  #   secrets: inherit
+  owasp-scanner:
+    needs: [ setup ]
+    uses: liquibase/build-logic/.github/workflows/owasp-scanner.yml@main
+    with:
+      branch: ${{ needs.setup.outputs.branch }}
+    secrets: inherit
 
-  # build-azure-uber-jar:
-  #  needs: [ setup]
-  #  uses: liquibase/liquibase/.github/workflows/build-azure-uber-jar.yml@master
-  #  with:
-  #    branch: ${{ needs.setup.outputs.branch }}
-  #    liquibase-version: ${{ needs.setup.outputs.version }}
-  #  secrets: inherit
+  build-azure-uber-jar:
+   needs: [ setup, owasp-scanner ]
+   uses: liquibase/liquibase/.github/workflows/build-azure-uber-jar.yml@master
+   with:
+     branch: ${{ needs.setup.outputs.branch }}
+     liquibase-version: ${{ needs.setup.outputs.version }}
+   secrets: inherit
   
   build-extension-jars:
-   needs: [ setup]
+   needs: [ setup, owasp-scanner ]
    uses: liquibase/liquibase/.github/workflows/build-extension-jars.yml@DAT-18103
    with:
      liquibase-version: ${{ needs.setup.outputs.version }}
@@ -175,7 +175,7 @@ jobs:
           
           ## Sign Files
           ## liquibase-azure-deps and liquibase extensions are already on its correct version. Check reusable workflow: build-azure-uber-jar.yml and build-extension-jars.yml
-          # mv liquibase-pro/liquibase-azure-deps/* re-version/out
+          #mv liquibase-pro/liquibase-azure-deps/* re-version/out
 
           # Modify the zip file
           unzip re-version/out/liquibase-${{ needs.setup.outputs.version }}.zip -d re-version/out/liquibase-${{ needs.setup.outputs.version }}
@@ -188,14 +188,14 @@ jobs:
           (cd re-version/out/ && zip -r liquibase-${{ needs.setup.outputs.version }}.zip liquibase-${{ needs.setup.outputs.version }} && rm -rf liquibase-${{ needs.setup.outputs.version }} && cd ../..)  
           
           # Modify the tar.gz file
-          #mkdir -p re-version/out/liquibase-${{ needs.setup.outputs.version }}
-          #tar -xzvf re-version/out/liquibase-${{ needs.setup.outputs.version }}.tar.gz -C re-version/out/liquibase-${{ needs.setup.outputs.version }}
-          #rm -rf re-version/out/liquibase-${{ needs.setup.outputs.version }}.tar.gz
-          #mkdir -p re-version/out/liquibase-${{ needs.setup.outputs.version }}/internal/extensions
-          #for I in "${EXT[@]}"; do
-            #cp ~/.m2/repository/org/liquibase/ext/$I/${{ needs.setup.outputs.version }}/$I-${{ needs.setup.outputs.version }}.jar re-version/out/liquibase-${{ needs.setup.outputs.version }}/internal/extensions/$I-${{ needs.setup.outputs.version }}.jar || echo "Failed to move $I artifact"
-          #done
-          #(cd re-version/out/ && tar -czvf liquibase-${{ needs.setup.outputs.version }}.tar.gz liquibase-${{ needs.setup.outputs.version }} && rm -rf liquibase-${{ needs.setup.outputs.version }} && cd ../..)
+          mkdir -p re-version/out/liquibase-${{ needs.setup.outputs.version }}
+          tar -xzvf re-version/out/liquibase-${{ needs.setup.outputs.version }}.tar.gz -C re-version/out/liquibase-${{ needs.setup.outputs.version }}
+          rm -rf re-version/out/liquibase-${{ needs.setup.outputs.version }}.tar.gz
+          mkdir -p re-version/out/liquibase-${{ needs.setup.outputs.version }}/internal/extensions
+          for I in "${EXT[@]}"; do
+            cp ~/.m2/repository/org/liquibase/ext/$I/${{ needs.setup.outputs.version }}/$I-${{ needs.setup.outputs.version }}.jar re-version/out/liquibase-${{ needs.setup.outputs.version }}/internal/extensions/$I-${{ needs.setup.outputs.version }}.jar || echo "Failed to move $I artifact"
+          done
+          (cd re-version/out/ && tar -czvf liquibase-${{ needs.setup.outputs.version }}.tar.gz liquibase-${{ needs.setup.outputs.version }} && rm -rf liquibase-${{ needs.setup.outputs.version }} && cd ../..)
 
           $PWD/.github/util/sign-artifacts.sh re-version/out
           
