♻️ (create-release.yml): comment out redundant steps for checking tag existence and attaching files to draft release to simplify workflow and improve maintainability

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -394,54 +394,54 @@ jobs:
           rm re-version/final/*.sha1
 
         # Check if the tag already exists in OSS repository, if it does, exit with error. This is to prevent the artifacts from being attached to the already released tag.
-      - name: Check OSS release tag existence, if tag exists, exit with error
-        run: |
-          tag="v${{ needs.setup.outputs.version }}"
-          if git show-ref --tags --quiet --verify -- "refs/tags/$tag"
-          then
-              echo "Tag $tag already exists"
-              exit 1
-          fi
+      # - name: Check OSS release tag existence, if tag exists, exit with error
+      #   run: |
+      #     tag="v${{ needs.setup.outputs.version }}"
+      #     if git show-ref --tags --quiet --verify -- "refs/tags/$tag"
+      #     then
+      #         echo "Tag $tag already exists"
+      #         exit 1
+      #     fi
 
-      - name: Attach Files to Draft Release
-        if: ${{ inputs.standalone_zip == false && inputs.dry_run == false }}
-        uses: softprops/action-gh-release@v2
-        with:
-          tag_name: v${{ needs.setup.outputs.version }}
-          fail_on_unmatched_files: true
-          body: Liquibase ${{ needs.setup.outputs.version }}
-          generate_release_notes: true
-          draft: true
-          files: re-version/final/*
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      # - name: Attach Files to Draft Release
+      #   if: ${{ inputs.standalone_zip == false && inputs.dry_run == false }}
+      #   uses: softprops/action-gh-release@v2
+      #   with:
+      #     tag_name: v${{ needs.setup.outputs.version }}
+      #     fail_on_unmatched_files: true
+      #     body: Liquibase ${{ needs.setup.outputs.version }}
+      #     generate_release_notes: true
+      #     draft: true
+      #     files: re-version/final/*
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Attach Files to Dry-Run Draft Release
-        id: attach-files-dry-run
-        if: ${{ inputs.standalone_zip == false && inputs.dry_run == true }}
-        uses: softprops/action-gh-release@v2
-        with:
-          tag_name: v${{ needs.setup.outputs.version }}
-          fail_on_unmatched_files: true
-          body: Liquibase ${{ needs.setup.outputs.version }} (Dry-Run)
-          generate_release_notes: true
-          draft: true
-          files: re-version/final/*
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      # - name: Attach Files to Dry-Run Draft Release
+      #   id: attach-files-dry-run
+      #   if: ${{ inputs.standalone_zip == false && inputs.dry_run == true }}
+      #   uses: softprops/action-gh-release@v2
+      #   with:
+      #     tag_name: v${{ needs.setup.outputs.version }}
+      #     fail_on_unmatched_files: true
+      #     body: Liquibase ${{ needs.setup.outputs.version }} (Dry-Run)
+      #     generate_release_notes: true
+      #     draft: true
+      #     files: re-version/final/*
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Extract dry-run release URL
-        if: ${{ inputs.standalone_zip == false && inputs.dry_run == true }}
-        id: extract-dry-run-url
-        shell: bash
-        run: |
-          assets_json=$(echo '${{ toJson(steps.attach-files-dry-run.outputs) }}' | jq -r '.assets | fromjson')
-          tar_gz_url=$(echo "$assets_json" | jq -r '.[] | select(.name | test("^liquibase-dry-run-.*\\.tar\\.gz$")) | .url')
-          zip_url=$(echo "$assets_json" | jq -r '.[] | select(.name | test("^liquibase-dry-run-.*\\.zip$")) | .url')
-          echo $tar_gz_url
-          echo $zip_url
-          echo "dry_run_tar_gz_url=$tar_gz_url" >> $GITHUB_OUTPUT
-          echo "dry_run_zip_url=$zip_url" >> $GITHUB_OUTPUT
+      # - name: Extract dry-run release URL
+      #   if: ${{ inputs.standalone_zip == false && inputs.dry_run == true }}
+      #   id: extract-dry-run-url
+      #   shell: bash
+      #   run: |
+      #     assets_json=$(echo '${{ toJson(steps.attach-files-dry-run.outputs) }}' | jq -r '.assets | fromjson')
+      #     tar_gz_url=$(echo "$assets_json" | jq -r '.[] | select(.name | test("^liquibase-dry-run-.*\\.tar\\.gz$")) | .url')
+      #     zip_url=$(echo "$assets_json" | jq -r '.[] | select(.name | test("^liquibase-dry-run-.*\\.zip$")) | .url')
+      #     echo $tar_gz_url
+      #     echo $zip_url
+      #     echo "dry_run_tar_gz_url=$tar_gz_url" >> $GITHUB_OUTPUT
+      #     echo "dry_run_zip_url=$zip_url" >> $GITHUB_OUTPUT
 
       - name: Attach standalone zip to Build
         if: ${{ inputs.standalone_zip == true && inputs.dry_run == false }}
