test keygen

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -74,56 +74,52 @@ jobs:
       - run: |
           echo "Creating version ${{ inputs.version }} from ${{ inputs.branch }} with artifacts from build ${{ inputs.runId }} "
 
-  # owasp-scanner:
-  #   needs: [ setup ]
-  #   uses: liquibase/build-logic/.github/workflows/owasp-scanner.yml@main
-  #   with:
-  #     branch: ${{ needs.setup.outputs.branch }}
-  #   secrets: inherit
+  owasp-scanner:
+    needs: [ setup ]
+    uses: liquibase/build-logic/.github/workflows/owasp-scanner.yml@main
+    with:
+      branch: ${{ needs.setup.outputs.branch }}
+    secrets: inherit
 
   build-azure-uber-jar:
-    #needs: [setup, owasp-scanner]
-    needs: [setup]
+    needs: [setup, owasp-scanner]
     uses: ./.github/workflows/build-azure-uber-jar.yml
     with:
       branch: ${{ needs.setup.outputs.branch }}
       liquibase-version: ${{ needs.setup.outputs.version }}
     secrets: inherit
 
-  # build-extension-jars:
-  #   #needs: [setup, owasp-scanner]
-  #   needs: [setup, owasp-scanner]
-  #   uses: ./.github/workflows/build-extension-jars.yml
-  #   with:
-  #     liquibase-version: ${{ needs.setup.outputs.version }}
-  #     dependencies: ${{ needs.setup.outputs.dependencies }}
-  #     extensions: ${{ needs.setup.outputs.extensions }}
-  #     branch: ${{ needs.setup.outputs.branch }}
-  #   secrets: inherit
+  build-extension-jars:
+    needs: [setup, owasp-scanner]
+    uses: ./.github/workflows/build-extension-jars.yml
+    with:
+      liquibase-version: ${{ needs.setup.outputs.version }}
+      dependencies: ${{ needs.setup.outputs.dependencies }}
+      extensions: ${{ needs.setup.outputs.extensions }}
+      branch: ${{ needs.setup.outputs.branch }}
+    secrets: inherit
 
-  # get-liquibase-checks-version:
-  #   needs: [setup]
-  #   if: ${{ contains(needs.setup.outputs.extensions, 'liquibase-checks') }}
-  #   runs-on: ubuntu-latest
-  #   outputs:
-  #     version: ${{ steps.extract-version.outputs.version }}
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #       with:
-  #         repository: liquibase/liquibase-checks
-  #         token: ${{ secrets.BOT_TOKEN }}
+  get-liquibase-checks-version:
+    needs: [setup]
+    if: ${{ contains(needs.setup.outputs.extensions, 'liquibase-checks') }}
+    runs-on: ubuntu-latest
+    outputs:
+      version: ${{ steps.extract-version.outputs.version }}
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          repository: liquibase/liquibase-checks
+          token: ${{ secrets.BOT_TOKEN }}
 
-  #     - id: extract-version
-  #       name: Extract version from pom.xml
-  #       shell: bash
-  #       run: |
-  #         VERSION=$(grep '<version>' pom.xml | head -n 1 | sed 's/.*<version>\(.*\)-SNAPSHOT<\/version>.*/\1/')
-  #         echo "version=$VERSION" >> $GITHUB_OUTPUT
+      - id: extract-version
+        name: Extract version from pom.xml
+        shell: bash
+        run: |
+          VERSION=$(grep '<version>' pom.xml | head -n 1 | sed 's/.*<version>\(.*\)-SNAPSHOT<\/version>.*/\1/')
+          echo "version=$VERSION" >> $GITHUB_OUTPUT
 
   reversion:
-    needs:
-      #[setup,build-azure-uber-jar,build-extension-jars,get-liquibase-checks-version]
-      [setup, build-azure-uber-jar]
+    needs: [setup,build-azure-uber-jar,build-extension-jars,get-liquibase-checks-version]
     name: Re-version artifacts ${{ needs.setup.outputs.version }}
     runs-on: ubuntu-22.04
     steps:
@@ -199,16 +195,16 @@ jobs:
               }
             ]
 
-      # - name: Get extensions artifacts
-      #   run: |
-      #     IFS=',' read -ra ADDR <<< "${{ needs.setup.outputs.extensions }}"
-      #     for extension in "${ADDR[@]}"; do
-      #       if [ "$extension" != "liquibase-checks" ]; then
-      #         mvn dependency:get -DgroupId=org.liquibase.ext -DartifactId=$extension -Dversion=${{ needs.setup.outputs.version }} -Dtransitive=false || echo "Failed to download $extension artifact"
-      #       else
-      #         mvn dependency:get -DgroupId=org.liquibase.ext -DartifactId=$extension -Dversion=${{ needs.get-liquibase-checks-version.outputs.version }} -Dtransitive=false || echo "Failed to download $extension artifact"
-      #       fi
-      #     done
+      - name: Get extensions artifacts
+        run: |
+          IFS=',' read -ra ADDR <<< "${{ needs.setup.outputs.extensions }}"
+          for extension in "${ADDR[@]}"; do
+            if [ "$extension" != "liquibase-checks" ]; then
+              mvn dependency:get -DgroupId=org.liquibase.ext -DartifactId=$extension -Dversion=${{ needs.setup.outputs.version }} -Dtransitive=false || echo "Failed to download $extension artifact"
+            else
+              mvn dependency:get -DgroupId=org.liquibase.ext -DartifactId=$extension -Dversion=${{ needs.get-liquibase-checks-version.outputs.version }} -Dtransitive=false || echo "Failed to download $extension artifact"
+            fi
+          done
 
       - name: Set up JDK
         uses: actions/setup-java@v4
@@ -405,54 +401,54 @@ jobs:
           rm re-version/final/*.sha1
 
         # Check if the tag already exists in OSS repository, if it does, exit with error. This is to prevent the artifacts from being attached to the already released tag.
-      # - name: Check OSS release tag existence, if tag exists, exit with error
-      #   run: |
-      #     tag="v${{ needs.setup.outputs.version }}"
-      #     if git show-ref --tags --quiet --verify -- "refs/tags/$tag"
-      #     then
-      #         echo "Tag $tag already exists"
-      #         exit 1
-      #     fi
+      - name: Check OSS release tag existence, if tag exists, exit with error
+        run: |
+          tag="v${{ needs.setup.outputs.version }}"
+          if git show-ref --tags --quiet --verify -- "refs/tags/$tag"
+          then
+              echo "Tag $tag already exists"
+              exit 1
+          fi
 
-      # - name: Attach Files to Draft Release
-      #   if: ${{ inputs.standalone_zip == false && inputs.dry_run == false }}
-      #   uses: softprops/action-gh-release@v2
-      #   with:
-      #     tag_name: v${{ needs.setup.outputs.version }}
-      #     fail_on_unmatched_files: true
-      #     body: Liquibase ${{ needs.setup.outputs.version }}
-      #     generate_release_notes: true
-      #     draft: true
-      #     files: re-version/final/*
-      #   env:
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Attach Files to Draft Release
+        if: ${{ inputs.standalone_zip == false && inputs.dry_run == false }}
+        uses: softprops/action-gh-release@v2
+        with:
+          tag_name: v${{ needs.setup.outputs.version }}
+          fail_on_unmatched_files: true
+          body: Liquibase ${{ needs.setup.outputs.version }}
+          generate_release_notes: true
+          draft: true
+          files: re-version/final/*
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      # - name: Attach Files to Dry-Run Draft Release
-      #   id: attach-files-dry-run
-      #   if: ${{ inputs.standalone_zip == false && inputs.dry_run == true }}
-      #   uses: softprops/action-gh-release@v2
-      #   with:
-      #     tag_name: v${{ needs.setup.outputs.version }}
-      #     fail_on_unmatched_files: true
-      #     body: Liquibase ${{ needs.setup.outputs.version }} (Dry-Run)
-      #     generate_release_notes: true
-      #     draft: true
-      #     files: re-version/final/*
-      #   env:
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Attach Files to Dry-Run Draft Release
+        id: attach-files-dry-run
+        if: ${{ inputs.standalone_zip == false && inputs.dry_run == true }}
+        uses: softprops/action-gh-release@v2
+        with:
+          tag_name: v${{ needs.setup.outputs.version }}
+          fail_on_unmatched_files: true
+          body: Liquibase ${{ needs.setup.outputs.version }} (Dry-Run)
+          generate_release_notes: true
+          draft: true
+          files: re-version/final/*
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      # - name: Extract dry-run release URL
-      #   if: ${{ inputs.standalone_zip == false && inputs.dry_run == true }}
-      #   id: extract-dry-run-url
-      #   shell: bash
-      #   run: |
-      #     assets_json=$(echo '${{ toJson(steps.attach-files-dry-run.outputs) }}' | jq -r '.assets | fromjson')
-      #     tar_gz_url=$(echo "$assets_json" | jq -r '.[] | select(.name | test("^liquibase-dry-run-.*\\.tar\\.gz$")) | .url')
-      #     zip_url=$(echo "$assets_json" | jq -r '.[] | select(.name | test("^liquibase-dry-run-.*\\.zip$")) | .url')
-      #     echo $tar_gz_url
-      #     echo $zip_url
-      #     echo "dry_run_tar_gz_url=$tar_gz_url" >> $GITHUB_OUTPUT
-      #     echo "dry_run_zip_url=$zip_url" >> $GITHUB_OUTPUT
+      - name: Extract dry-run release URL
+        if: ${{ inputs.standalone_zip == false && inputs.dry_run == true }}
+        id: extract-dry-run-url
+        shell: bash
+        run: |
+          assets_json=$(echo '${{ toJson(steps.attach-files-dry-run.outputs) }}' | jq -r '.assets | fromjson')
+          tar_gz_url=$(echo "$assets_json" | jq -r '.[] | select(.name | test("^liquibase-dry-run-.*\\.tar\\.gz$")) | .url')
+          zip_url=$(echo "$assets_json" | jq -r '.[] | select(.name | test("^liquibase-dry-run-.*\\.zip$")) | .url')
+          echo $tar_gz_url
+          echo $zip_url
+          echo "dry_run_tar_gz_url=$tar_gz_url" >> $GITHUB_OUTPUT
+          echo "dry_run_zip_url=$zip_url" >> $GITHUB_OUTPUT
 
       - name: Attach standalone zip to Build
         if: ${{ inputs.standalone_zip == true && inputs.dry_run == false }}
